######################################################################
# Automatically generated by qmake (2.01a) Tue Oct 1 16:43:14 2013
######################################################################

QT += opengl

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += GLPolygon.h GLPolygonWidget.h GLPolygonWindow.h GLPolygonController.h
SOURCES += GLPolygonWidget.cpp GLPolygonWindow.cpp GLPolygon.cpp main.cpp GLPolygonController.cpp
